from pathlib import Path
root=Path(__file__).resolve().parents[1]
engine=(root/'js/three.min.js').read_text().rstrip('\n')  # 4.3.73: three.js moved out of game.html
world=(root/'assets/city-v2/world.js').read_text()
html='''<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Zombie Survival · Nuova città 3D</title><style>
*{box-sizing:border-box}body{margin:0;overflow:hidden;background:#a8b0a1;color:#f2efdf;font:14px system-ui,sans-serif}canvas{display:block;touch-action:none}.panel{position:fixed;top:16px;left:16px;right:16px;display:flex;justify-content:space-between;gap:14px;pointer-events:none}.card{background:rgba(26,34,27,.9);border:1px solid #61705a;border-radius:16px;padding:14px 18px;box-shadow:0 8px 30px #16221b55;pointer-events:auto;backdrop-filter:blur(12px)}h1{font-size:19px;margin:0 0 4px}p{margin:0;color:#c3cbb8;font-size:12px}button{background:#46553f;color:#f2efdf;border:1px solid #819175;border-radius:9px;padding:9px 12px;font:600 12px system-ui;cursor:pointer}button:hover,button.active{background:#879768;color:#15201b}.controls{min-width:0;flex:1;display:flex;gap:7px;align-items:center;flex-wrap:wrap}.bottom{position:fixed;bottom:18px;left:16px;right:16px;display:flex;justify-content:space-between;align-items:end;gap:12px;pointer-events:none}.districts{max-width:650px;pointer-events:auto;display:flex;gap:6px;flex-wrap:wrap}.hint{background:#223128d9;padding:10px 14px;border-radius:10px;font-size:12px;color:#d0d6c7}.pad{display:none;grid-template-columns:repeat(3,42px);grid-template-rows:repeat(2,42px);gap:4px;pointer-events:auto}.pad button{padding:0;font-size:18px;touch-action:none}.pad .forward{grid-column:2}.walk .pad{display:grid}.walk .districts{display:none}.badge{font-size:10px;letter-spacing:1.4px;color:#cad4a3;text-transform:uppercase;margin-bottom:7px}.note{position:fixed;bottom:3px;right:10px;font-size:9px;color:#d8dfcd}#error{position:fixed;inset:40%;background:#243125;padding:20px;display:none}
@media(max-width:650px){.panel{top:9px;left:9px;right:9px}.card{padding:10px 12px}h1{font-size:14px}.controls{gap:4px;justify-content:flex-end}.controls button{padding:7px 8px}.stats{display:none}.bottom{left:9px;right:9px;bottom:20px}.hint{max-width:190px;font-size:10px}.districts button{padding:7px 9px;font-size:10px}.badge{font-size:8px}.intro{width:48%;min-width:0;flex:0 0 48%}}
</style></head><body><div class="panel"><div class="card intro"><div class="badge">Zombie Survival · Progetto città nuova</div><h1>Una città da esplorare</h1><p id="stats" class="stats"></p><p>Prima versione 3D · grafica in lavorazione</p></div><div class="card controls"><button id="orbit" class="active">Vista città</button><button id="walk">Cammina</button><button id="zoomIn" aria-label="Avvicina">+</button><button id="zoomOut" aria-label="Allontana">−</button></div></div><div class="bottom"><div id="districts" class="districts"></div><div class="pad"><button class="forward" data-key="KeyW" aria-label="Avanti">↑</button><button data-key="KeyA" aria-label="Sinistra">←</button><button data-key="KeyS" aria-label="Indietro">↓</button><button data-key="KeyD" aria-label="Destra">→</button></div><div class="hint" id="hint">Trascina per ruotare · pizzica o usa ＋ e − per lo zoom</div></div><div class="note">Anteprima reale del modello 3D · immagine artistica separata dal risultato</div><div id="error">Il dispositivo non ha avviato la vista 3D.</div><script>'''+engine+'</script><script>'+world+'''</script><script>
try{
const T=window.THREE,scene=new T.Scene();scene.background=new T.Color(0xaeb7a7);scene.fog=new T.Fog(0xaeb7a7,220,600);
const renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;document.body.prepend(renderer.domElement);
const camera=new T.PerspectiveCamera(52,innerWidth/innerHeight,.08,800);const hemi=new T.HemisphereLight(0xe2e2cf,0x424e38,1.1);scene.add(hemi);const sun=new T.DirectionalLight(0xffead0,2);sun.position.set(-80,120,70);scene.add(sun);
let lightMode=1;const lightButton=document.createElement('button');lightButton.id='lightMode';document.querySelector('.controls').append(lightButton);
function atmosphere(){const settings=[['Giorno',0xaeb7a7,1.1,2],['Crepuscolo',0x768278,.75,.8],['Notte',0x293730,.48,.22]][lightMode];lightButton.textContent=settings[0];lightButton.setAttribute('aria-label','Illuminazione: '+settings[0]+'. Tocca per cambiare');scene.background.setHex(settings[1]);scene.fog.color.setHex(settings[1]);hemi.intensity=settings[2];sun.intensity=settings[3];}lightButton.onclick=()=>{lightMode=(lightMode+1)%3;atmosphere();};atmosphere();
const terrain=new T.Mesh(new T.PlaneGeometry(600,600),new T.MeshLambertMaterial({color:0x70785b}));terrain.rotation.x=-Math.PI/2;scene.add(terrain);
const boxes=[],circles=[],solids=[],houses=[];const city=buildCityV2(T,{scene,boxes,circles,solids,houses,anisotropy:renderer.capabilities.getMaxAnisotropy()});
window.__preview={scene,camera,renderer,city,boxes,circles};
document.getElementById('stats').textContent=city.stats.buildings+' edifici · '+city.stats.roads+' strade · '+city.stats.trees+' alberi · area 336 × 336 m';
let mode='orbit',angle=.65,elevation=.77,distance=300,target=new T.Vector3(0,0,-12),yaw=0,pitch=0;const pos=new T.Vector3(-122,1.7,75),keys={};
function setMode(v){mode=v;document.body.classList.toggle('walk',v==='walk');document.getElementById('walk').classList.toggle('active',v==='walk');document.getElementById('orbit').classList.toggle('active',v==='orbit');document.getElementById('hint').textContent=v==='walk'?'Trascina per guardare · frecce per camminare · WASD su PC':'Trascina per ruotare · pizzica o usa ＋ e − per lo zoom';}
document.getElementById('orbit').onclick=()=>setMode('orbit');document.getElementById('walk').onclick=()=>setMode('walk');document.getElementById('zoomIn').onclick=()=>distance=Math.max(18,distance*.8);document.getElementById('zoomOut').onclick=()=>distance=Math.min(460,distance*1.2);
for(const [label,x,z] of [['Rifugio',-122,72],['Piazza',0,-24],['Residenze',-57,-24],['Ospedale',112,-72],['Polizia',112,-24],['Mercato',0,24],['Fabbriche',112,72],['Stazione',0,-120],['Relitti',87,-42]]){const b=document.createElement('button');b.textContent=label;b.onclick=()=>{if(mode==='walk'){pos.set(x,1.7,z+17);yaw=0;}else{target.set(x,0,z);distance=label==='Relitti'?28:60;elevation=.6;}};document.getElementById('districts').append(b);}
const pointers=new Map();let pinch=0;const cv=renderer.domElement;
cv.onpointerdown=e=>{cv.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});pinch=0;};
cv.onpointermove=e=>{if(!pointers.has(e.pointerId))return;const old=pointers.get(e.pointerId),dx=e.clientX-old.x,dy=e.clientY-old.y;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const a=[...pointers.values()],d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);if(pinch&&mode==='orbit')distance=Math.max(18,Math.min(460,distance*pinch/d));pinch=d;return;}if(mode==='orbit'){angle-=dx*.007;elevation=Math.max(.12,Math.min(1.42,elevation+dy*.006));}else{yaw-=dx*.005;pitch=Math.max(-1.1,Math.min(1.1,pitch-dy*.005));}};
cv.onpointerup=cv.onpointercancel=e=>{pointers.delete(e.pointerId);pinch=0;};cv.addEventListener('wheel',e=>{e.preventDefault();distance=Math.max(18,Math.min(460,distance*Math.exp(e.deltaY*.001)));},{passive:false});
addEventListener('keydown',e=>{if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code)){e.preventDefault();keys[e.code]=true;}});addEventListener('keyup',e=>keys[e.code]=false);addEventListener('blur',()=>{for(const k in keys)keys[k]=false;});
document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[b.dataset.key]=true;};b.onpointerup=b.onpointercancel=()=>keys[b.dataset.key]=false;});
function free(x,z){return Math.abs(x)<166&&Math.abs(z)<166&&!boxes.some(b=>x>b.x0-.35&&x<b.x1+.35&&z>b.z0-.35&&z<b.z1+.35)&&!circles.some(c=>Math.hypot(x-c.x,z-c.z)<c.r+.35);}
let last=performance.now();function frame(now){const dt=Math.min(.04,(now-last)/1000);last=now;if(mode==='orbit'){camera.position.set(target.x+Math.sin(angle)*distance*Math.cos(elevation),distance*Math.sin(elevation),target.z+Math.cos(angle)*distance*Math.cos(elevation));camera.lookAt(target);}else{let a=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0),f=(keys.KeyW||keys.ArrowUp?1:0)-(keys.KeyS||keys.ArrowDown?1:0),n=Math.hypot(a,f)||1;const dx=(a*Math.cos(yaw)-f*Math.sin(yaw))*dt*6/n,dz=(-a*Math.sin(yaw)-f*Math.cos(yaw))*dt*6/n;if(free(pos.x+dx,pos.z))pos.x+=dx;if(free(pos.x,pos.z+dz))pos.z+=dz;camera.position.copy(pos);camera.rotation.set(pitch,yaw,0,'YXZ');}city.update(now/1000,camera,renderer.domElement.height);renderer.render(scene,camera);requestAnimationFrame(frame);}requestAnimationFrame(frame);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
}catch(e){document.getElementById('error').style.display='block';console.error(e);}
</script></body></html>'''
(root/'city-preview.html').write_text(html)
print('Portable city preview written:',len(html))
